---
JoinBroadcast1: §9/=======================
LEER: " "
JoinBroadcast2: ' §8» §6Du Bist auf Paincraft Gerade Gejoint!'
JoinBroadcast3: ' §8» §fWEBSITE§7 × §5Wird Es Nicht Geben'
JoinBroadcast4: ' §8» §fDISCORD§7 × §5https://discord.gg/fV93frR'
LEER2: " "
JoinBroadcast5: §9=======================
BlockBreakMessage: ' §cDu Darfst nicht Abbauen'
Hub/Lobby: ' §c Willkommen in der Lobby'
JoinTitle: ' §7[§a»§7] §aWllkommen'
Prefix: §7[§6§lLOBBY§r§7]
Chat: ' §3Du musst den Rang §6Premium§3 besitzen um schreiben zu koennen!'
...
